# Form implementation generated from reading ui file 'login_form2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(680, 592)
        Form.setStyleSheet("")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(120, 120, 411, 361))
        self.frame.setStyleSheet("QFrame{\n"
"background:#333;\n"
"border-radius:30px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_loginhere = QtWidgets.QLabel(parent=self.frame)
        self.label_loginhere.setGeometry(QtCore.QRect(100, 50, 261, 41))
        self.label_loginhere.setStyleSheet("*{\n"
"color:white;\n"
"font-family:century gothic;\n"
"font-size:24px;\n"
"}")
        self.label_loginhere.setObjectName("label_loginhere")
        self.lineEdit_username = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_username.setGeometry(QtCore.QRect(20, 120, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setStyleSheet("#lineEdit_username{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}")
        self.lineEdit_username.setText("")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_password.setGeometry(QtCore.QRect(20, 190, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("#lineEdit_password{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.check_button_password = QtWidgets.QCheckBox(parent=self.frame)
        self.check_button_password.setGeometry(QtCore.QRect(20, 230, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.check_button_password.setFont(font)
        self.check_button_password.setStyleSheet("#check_button_password{\n"
"color:#717072;\n"
"border-radius:20px;\n"
"border-bottom:1 px solid #717072;\n"
"}")
        self.check_button_password.setObjectName("check_button_password")
        self.pushButton_login = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_login.setGeometry(QtCore.QRect(40, 260, 331, 21))
        self.pushButton_login.setStyleSheet("#pushButton_login{\n"
"color:white;\n"
"background:pink;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_login_teacher = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_login_teacher.setGeometry(QtCore.QRect(40, 290, 331, 24))
        self.pushButton_login_teacher.setStyleSheet("#pushButton_login_teacher{\n"
"color:white;\n"
"background:pink;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_login_teacher.setObjectName("pushButton_login_teacher")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(parent=self.frame)
        self.commandLinkButton.setGeometry(QtCore.QRect(30, 320, 341, 31))
        self.commandLinkButton.setStyleSheet("#commandLinkButton{\n"
"color:white;\n"
"}")
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, -10, 81, 81))
        self.frame_2.setStyleSheet("border-image: url(:/images2/mortarboard.png);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setGeometry(QtCore.QRect(320, 60, 81, 71))
        self.frame_3.setStyleSheet("border-image: url(:/images2/document.png);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_loginhere.setText(_translate("Form", "   L   O   G   I   N "))
        self.lineEdit_username.setPlaceholderText(_translate("Form", "Username"))
        self.lineEdit_password.setPlaceholderText(_translate("Form", "Password"))
        self.check_button_password.setText(_translate("Form", "Show"))
        self.pushButton_login.setText(_translate("Form", "LOGIN"))
        self.pushButton_login_teacher.setText(_translate("Form", "TEACHER"))
        self.commandLinkButton.setText(_translate("Form", "Don\'t You Have A Account? Sıgn Up Here!"))
