# Form implementation generated from reading ui file 'register_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 591)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(140, 90, 491, 391))
        self.frame.setStyleSheet("QFrame{\n"
"background:#333;\n"
"border-radius:30px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_mailadress = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_mailadress.setGeometry(QtCore.QRect(30, 120, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_mailadress.setFont(font)
        self.lineEdit_mailadress.setStyleSheet("#lineEdit_mailadress{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}")
        self.lineEdit_mailadress.setText("")
        self.lineEdit_mailadress.setObjectName("lineEdit_mailadress")
        self.lineEdit_username_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_username_2.setGeometry(QtCore.QRect(30, 180, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_username_2.setFont(font)
        self.lineEdit_username_2.setStyleSheet("#lineEdit_username_2{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}")
        self.lineEdit_username_2.setText("")
        self.lineEdit_username_2.setObjectName("lineEdit_username_2")
        self.lineEdit_password_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_password_2.setGeometry(QtCore.QRect(30, 240, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_password_2.setFont(font)
        self.lineEdit_password_2.setStyleSheet("#lineEdit_password_2{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}")
        self.lineEdit_password_2.setText("")
        self.lineEdit_password_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password_2.setObjectName("lineEdit_password_2")
        self.check_button_password_2 = QtWidgets.QCheckBox(parent=self.frame)
        self.check_button_password_2.setGeometry(QtCore.QRect(30, 290, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.check_button_password_2.setFont(font)
        self.check_button_password_2.setStyleSheet("#check_button_password_2{\n"
"color:#717072;\n"
"border-radius:20px;\n"
"border-bottom:1 px solid #717072;\n"
"}")
        self.check_button_password_2.setObjectName("check_button_password_2")
        self.toolButton_teacher = QtWidgets.QToolButton(parent=self.frame)
        self.toolButton_teacher.setGeometry(QtCore.QRect(80, 330, 161, 22))
        self.toolButton_teacher.setStyleSheet("#toolButton_teacher{\n"
"color:white;\n"
"background:pink;\n"
"border-radius:10px;\n"
"}")
        self.toolButton_teacher.setObjectName("toolButton_teacher")
        self.toolButton_student = QtWidgets.QToolButton(parent=self.frame)
        self.toolButton_student.setGeometry(QtCore.QRect(280, 330, 141, 22))
        self.toolButton_student.setStyleSheet("#toolButton_student{\n"
"color:white;\n"
"background:pink;\n"
"border-radius:10px;\n"
"}")
        self.toolButton_student.setObjectName("toolButton_student")
        self.pushButton_icon = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_icon.setGeometry(QtCore.QRect(300, 20, 171, 141))
        self.pushButton_icon.setStyleSheet("#pushButton_icon{\n"
"\n"
"background:pink;\n"
"border-radius:60px;\n"
"}")
        self.pushButton_icon.setText("")
        self.pushButton_icon.setObjectName("pushButton_icon")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 80, 171, 20))
        self.label.setStyleSheet("*{\n"
"color:white;\n"
"font-family:century gothic;\n"
"font-size:24px;\n"
"}")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_mailadress.setPlaceholderText(_translate("MainWindow", "E-Mail Adress*"))
        self.lineEdit_username_2.setPlaceholderText(_translate("MainWindow", "Username*"))
        self.lineEdit_password_2.setPlaceholderText(_translate("MainWindow", "Password*"))
        self.check_button_password_2.setText(_translate("MainWindow", "Show"))
        self.toolButton_teacher.setText(_translate("MainWindow", "Teacher"))
        self.toolButton_student.setText(_translate("MainWindow", "Student"))
        self.label.setText(_translate("MainWindow", "  R E G I S T E R "))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    register_form = Ui_MainWindow()
    register_form.show()
    sys.exit(app.exec())