# Form implementation generated from reading ui file 'teacher_login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form1):
        Form1.setObjectName("Form1")
        Form1.resize(771, 627)
        self.pushButton_icon_teacher = QtWidgets.QPushButton(parent=Form1)
        self.pushButton_icon_teacher.setGeometry(QtCore.QRect(290, 90, 171, 141))
        self.pushButton_icon_teacher.setStyleSheet("#pushButton_icon_teacher{\n"
"background:pink;\n"
"border-radius:60px;\n"
"}")
        self.pushButton_icon_teacher.setText("")
        self.pushButton_icon_teacher.setObjectName("pushButton_icon_teacher")
        self.frame_teacher = QtWidgets.QFrame(parent=Form1)
        self.frame_teacher.setGeometry(QtCore.QRect(170, 160, 411, 361))
        self.frame_teacher.setStyleSheet("QFrame{\n"
"background:#333;\n"
"border-radius:30px;\n"
"}")
        self.frame_teacher.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_teacher.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_teacher.setObjectName("frame_teacher")
        self.lineEdit_username_teacher = QtWidgets.QLineEdit(parent=self.frame_teacher)
        self.lineEdit_username_teacher.setGeometry(QtCore.QRect(20, 120, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_username_teacher.setFont(font)
        self.lineEdit_username_teacher.setStyleSheet("#lineEdit_username_teacher{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}")
        self.lineEdit_username_teacher.setText("")
        self.lineEdit_username_teacher.setObjectName("lineEdit_username_teacher")
        self.lineEdit_password_teacher = QtWidgets.QLineEdit(parent=self.frame_teacher)
        self.lineEdit_password_teacher.setGeometry(QtCore.QRect(20, 190, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_password_teacher.setFont(font)
        self.lineEdit_password_teacher.setStyleSheet("#lineEdit_password_teacher{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}")
        self.lineEdit_password_teacher.setText("")
        self.lineEdit_password_teacher.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password_teacher.setObjectName("lineEdit_password_teacher")
        self.check_button_password_teacher = QtWidgets.QCheckBox(parent=self.frame_teacher)
        self.check_button_password_teacher.setGeometry(QtCore.QRect(20, 230, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.check_button_password_teacher.setFont(font)
        self.check_button_password_teacher.setStyleSheet("#check_button_password_teacher{\n"
"color:#717072;\n"
"border-radius:20px;\n"
"border-bottom:1 px solid #717072;\n"
"}")
        self.check_button_password_teacher.setObjectName("check_button_password_teacher")
        self.pushButton_login_teacher = QtWidgets.QPushButton(parent=self.frame_teacher)
        self.pushButton_login_teacher.setGeometry(QtCore.QRect(40, 280, 331, 21))
        self.pushButton_login_teacher.setStyleSheet("#pushButton_login_teacher{\n"
"color:white;\n"
"background:pink;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_login_teacher.setObjectName("pushButton_login_teacher")
        self.commandLinkButton_teacher = QtWidgets.QCommandLinkButton(parent=self.frame_teacher)
        self.commandLinkButton_teacher.setGeometry(QtCore.QRect(30, 320, 341, 31))
        self.commandLinkButton_teacher.setStyleSheet("#commandLinkButton_teacher{\n"
"color:white;\n"
"}")
        self.commandLinkButton_teacher.setObjectName("commandLinkButton_teacher")
        self.label_loginhere = QtWidgets.QLabel(parent=Form1)
        self.label_loginhere.setGeometry(QtCore.QRect(320, 150, 111, 21))
        self.label_loginhere.setStyleSheet("*{\n"
"color:white;\n"
"font-family:century gothic;\n"
"font-size:17px;\n"
"}")
        self.label_loginhere.setObjectName("label_loginhere")
        self.frame_teacher.raise_()
        self.pushButton_icon_teacher.raise_()
        self.label_loginhere.raise_()

        self.retranslateUi(Form1)
        QtCore.QMetaObject.connectSlotsByName(Form1)

    def retranslateUi(self, Form1):
        _translate = QtCore.QCoreApplication.translate
        Form1.setWindowTitle(_translate("Form1", "Form"))
        self.lineEdit_username_teacher.setPlaceholderText(_translate("Form1", "Username*"))
        self.lineEdit_password_teacher.setPlaceholderText(_translate("Form1", "Password*"))
        self.check_button_password_teacher.setText(_translate("Form1", "Show"))
        self.pushButton_login_teacher.setText(_translate("Form1", "LOGIN"))
        self.commandLinkButton_teacher.setText(_translate("Form1", "Don\'t You Have A Account? Sıgn Up Here!"))
        self.label_loginhere.setText(_translate("Form1", "  T E A C H E R"))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    teacher_form = Ui_Form1()
    teacher_form.show()
    sys.exit(app.exec())